ENCODER_MAP_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes

# Size optimisations
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
SEND_STRING_ENABLE = no
